# Grantmaker settings
foundation_name: The Example Foundation
foundation_tagline: Advancing the adoption of open source technology among progressive funders
grant_application_login: https://www.grantinterface.com/Common/LogOn.aspx?eqs=kw_123456_EXAMPLE

# Social media settings
# Enter the full profile url (e.g. https://twitter.com/smartergiving)
profile_twitter: https://twitter.com/examplefdn
profile_facebook: https://facebook.com/the-example-foundation
profile_instagram: 
profile_github: 

# Site settings
title: # Defaults to foundation_name if left blank
description: > # this means to start on the next line (which needs to be indented two spaces)"
  The Example Foundation erat sit proin magnis duis, vulputate wisi vel hac, sed justo turpis leo sit hac mauris, maecenas sem dapibus neque malesuada ante, congue arcu..

# Google settings
live: false # enter 'true' when you're ready for the site to be indexed by Google and other web crawlers

# Jekyll settings
baseurl: /foundation-website-template # Leave this blank unless your site is located on a subpath, e.g. /blog
url: https://smartergiving.org # Typically http://www.yourdomain.org
collections:
  featured-cards:
    output: true
sass:
  sass_dir: assets/css/_sass

# Build settings
markdown: kramdown
kramdown:
  input: GFM
exclude: 
  - README.md
  - /images/photoshop-helpers
